### ISSUE TITLE
Fix page titles and favicon on all pages

### ISSUE THREAD

**Issue by krharsh17** [hackslash-nitp/hackslash-nitp.github.io#35]
Currently, 'hackslash index' is shown on all pages' title bars. Change that to the page name in each case. Also, put the favicon ([this icon](https://github.com/hackslash-nitp/hackslash-nitp.github.io/blob/development/hackslash.ico)) for every page.

**Comment by supu2701** [comment]
I want to solve this issue. Can I start working on this and create a pull request?

**Comment by krharsh17** [comment]
Yes
