### ISSUE TITLE
Add space between 'Create Account' button and bottom margin of the login popup in all pages

### ISSUE THREAD

**Issue by krharsh17** [hackslash-nitp/hackslash-nitp.github.io#37]
![Screenshot (180)](https://user-images.githubusercontent.com/46624829/76880386-95c39b00-689d-11ea-8d8b-c8fdf34c20e0.png)

**Comment by ashk3301** [comment]
Sir I would like to fix this one.

**Comment by krharsh17** [comment]
Sure, go ahead!
