### ISSUE TITLE
Make the login popup responsive for narrow screens

### ISSUE THREAD

**Issue by krharsh17** [hackslash-nitp/hackslash-nitp.github.io#40]
This is how it looks currently:
![Screenshot (181)](https://user-images.githubusercontent.com/46624829/76880797-36b25600-689e-11ea-9bdc-0db0d98be885.png)

Discuss mobile design with a project mentor before beginning

**Comment by divided7** [comment]
Are there any prototypes available for mobile screens?

**Comment by krharsh17** [comment]
Unfortunately no. We're working, but it is going to take a while I guess.

**Comment by krharsh17** [comment]
1.
